apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: udagram-api
  name: udagram-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-api
    spec:
      containers:
        - image: xthian82/udagram-api
          name: udagram-api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
