apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api
  labels:
    service: udagram-api

spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-api
  template:
    metadata:
      labels:
        service: udagram-api
    spec:
      containers:
        - name: udagram-api
          image: xthian82/udagram-api
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api
  name: udagram-api-svc
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: udagram-api
